version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    command: ["sh", "-c", "echo 'Running migrations...' && npx knex --knexfile /usr/src/app/src/app/db/knexfile.ts migrate:latest && echo 'Running seeds...' && npx knex --knexfile /usr/src/app/src/app/db/knexfile.ts seed:run && echo 'Starting the app...' && npm run start"]

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: